name: Update Version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'The version bump to apply [possible values: major, minor, patch]'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      publish:
        description: 'Publish the package to GitHub releases and PyPI'
        required: false
        type: boolean
        default: true

jobs:
  update-version:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Do a version bump on the package
      - name: Update version by bumping git tag
        uses: leonsteinhaeuser/git-tag-bump@v1.1.0
        with:
          args: >-
            --bump ${{ github.event.inputs.bump }} --v-prefix --create --actor-name "GitHub Actions" --actor-mail "github-actions[bot]@users.noreply.github.com"

      - name: Get new version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

  build-and-publish:
    runs-on: ubuntu-latest
    needs:
      - update-version
    permissions:
      contents: write
      id-token: write

    if: github.event.inputs.publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.24"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build package
        run: uv build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.update-version.outputs.VERSION }}
          release_name: Release ${{ needs.update-version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Publish to PyPI
        run: uv publish

  build-and-publish-docs:
    runs-on: ubuntu-latest
    needs:
      - update-version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.24"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --extra viz --group docs

      - name: Build the documentation
        run: uv run make html -C docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
